### ISSUE TITLE
[♻️ ] 모달 컴퍼넌트 리팩토링  ( TODO : 함수넘기기)

### ISSUE THREAD

**Issue by suhong99** [ssgfinal/frontend-final#70]
### Issue 내용

-  모달 컴퍼넌트에서 텍스트를 외부에서 넘기도록 수정
- 컴퍼넌트를 여러번 호출하지 않도록 수정
### 진행 상황

- [x] 1  모달 코드 리팩토링
![image](https://github.com/ssgfinal/frontend-final/assets/120103909/4cdeab00-f351-41ca-98e7-44e7a34c9014)

- [x] 2 호출한 부분 이에 맞게 리팩토링
![image](https://github.com/ssgfinal/frontend-final/assets/120103909/bfb7c8ab-646f-457c-ade8-6ac134e0d7da)

- [x] 3 추후 함수 작동까지 확장을 위한  modalState 리팩토링
![image](https://github.com/ssgfinal/frontend-final/assets/120103909/2641bfdf-5cf1-401c-be7e-9803e6c36369)

함수 넘기는 코드 작성후에 modalComp or Fucn 삭제 예쩡 ==> 직렬화 오류로 인해서 함수를 직접적으로 전달할 수는 없음.
